/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeaderItem: typeof import('./../src/components/app/header-item.vue')['default']
    AppModal: typeof import('./../src/components/app/modal.vue')['default']
    AppPage: typeof import('./../src/components/app/page.vue')['default']
    IArrowNarrowLeft: typeof import('~icons/tabler/arrow-narrow-left')['default']
    IArrowNarrowRight: typeof import('~icons/tabler/arrow-narrow-right')['default']
    IAward: typeof import('~icons/tabler/award')['default']
    IBook: typeof import('~icons/tabler/book')['default']
    IBulb: typeof import('~icons/tabler/bulb')['default']
    IClock: typeof import('~icons/tabler/clock')['default']
    IDownload: typeof import('~icons/tabler/download')['default']
    IInfoCircle: typeof import('~icons/tabler/info-circle')['default']
    IMathSymbols: typeof import('~icons/tabler/math-symbols')['default']
    IMenu2: typeof import('~icons/tabler/menu2')['default']
    IQuestionMark: typeof import('~icons/tabler/question-mark')['default']
    ISmartHome: typeof import('~icons/tabler/smart-home')['default']
    IUsers: typeof import('~icons/tabler/users')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
